name: HF clone

on:
  push:
    branches:
      - "clone-model"
  workflow_dispatch:
    inputs:
      url:
        description: "url to download"
        required: true
      ossPath:
        default: "oss://oneflow-static/hf_hub"
        required: false
        description: "path to put file"

concurrency:
  group: clone-hub-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clone_model:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          overprovision-lvm: "true"
      - env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        run: |
          set -x
          mkdir -p $HOME/bin
          curl http://gosspublic.alicdn.com/ossutil/1.6.19/ossutil64 -o $HOME/bin/ossutil64
          chmod 755 $HOME/bin/ossutil64
          export PATH=$PATH:$HOME/bin
          ossutil64 config -e oss-cn-beijing.aliyuncs.com -i ${OSS_ACCESS_KEY_ID} -k ${OSS_ACCESS_KEY_SECRET}  -L EN -c $HOME/.ossutilconfig

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/safety_checker/model.fp16.safetensors
          ossutil64 cp -f model.fp16.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/safety_checker/model.fp16.safetensors
          rm model.fp16.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/safety_checker/model.safetensors
          ossutil64 cp -f model.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/safety_checker/model.safetensors
          rm model.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/safety_checker/pytorch_model.bin
          ossutil64 cp -f pytorch_model.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/safety_checker/pytorch_model.bin
          rm pytorch_model.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/safety_checker/pytorch_model.fp16.bin
          ossutil64 cp -f pytorch_model.fp16.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/safety_checker/pytorch_model.fp16.bin
          rm pytorch_model.fp16.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/model.fp16.safetensors
          ossutil64 cp -f model.fp16.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/text_encoder/model.fp16.safetensors
          rm model.fp16.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/model.safetensors
          ossutil64 cp -f model.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/text_encoder/model.safetensors
          rm model.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/pytorch_model.bin
          ossutil64 cp -f pytorch_model.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/text_encoder/pytorch_model.bin
          rm pytorch_model.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/pytorch_model.fp16.bin
          ossutil64 cp -f pytorch_model.fp16.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/text_encoder/pytorch_model.fp16.bin
          rm pytorch_model.fp16.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.bin
          ossutil64 cp -f diffusion_pytorch_model.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/unet/diffusion_pytorch_model.bin
          rm diffusion_pytorch_model.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.fp16.bin
          ossutil64 cp -f diffusion_pytorch_model.fp16.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/unet/diffusion_pytorch_model.fp16.bin
          rm diffusion_pytorch_model.fp16.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.fp16.safetensors
          ossutil64 cp -f diffusion_pytorch_model.fp16.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/unet/diffusion_pytorch_model.fp16.safetensors
          rm diffusion_pytorch_model.fp16.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.non_ema.bin
          ossutil64 cp -f diffusion_pytorch_model.non_ema.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/unet/diffusion_pytorch_model.non_ema.bin
          rm diffusion_pytorch_model.non_ema.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.non_ema.safetensors
          ossutil64 cp -f diffusion_pytorch_model.non_ema.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/unet/diffusion_pytorch_model.non_ema.safetensors
          rm diffusion_pytorch_model.non_ema.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.safetensors
          ossutil64 cp -f diffusion_pytorch_model.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/unet/diffusion_pytorch_model.safetensors
          rm diffusion_pytorch_model.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
          ossutil64 cp -f v1-5-pruned-emaonly.ckpt oss://oneflow-static/hf_hub/stable-diffusion-v1-5/v1-5-pruned-emaonly.ckpt
          rm v1-5-pruned-emaonly.ckpt

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors
          ossutil64 cp -f v1-5-pruned-emaonly.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/v1-5-pruned-emaonly.safetensors
          rm v1-5-pruned-emaonly.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.ckpt
          ossutil64 cp -f v1-5-pruned.ckpt oss://oneflow-static/hf_hub/stable-diffusion-v1-5/v1-5-pruned.ckpt
          rm v1-5-pruned.ckpt

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.safetensors
          ossutil64 cp -f v1-5-pruned.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/v1-5-pruned.safetensors
          rm v1-5-pruned.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.bin
          ossutil64 cp -f diffusion_pytorch_model.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/vae/diffusion_pytorch_model.bin
          rm diffusion_pytorch_model.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.fp16.bin
          ossutil64 cp -f diffusion_pytorch_model.fp16.bin oss://oneflow-static/hf_hub/stable-diffusion-v1-5/vae/diffusion_pytorch_model.fp16.bin
          rm diffusion_pytorch_model.fp16.bin

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.fp16.safetensors
          ossutil64 cp -f diffusion_pytorch_model.fp16.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/vae/diffusion_pytorch_model.fp16.safetensors
          rm diffusion_pytorch_model.fp16.safetensors

          wget --quiet https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.safetensors
          ossutil64 cp -f diffusion_pytorch_model.safetensors oss://oneflow-static/hf_hub/stable-diffusion-v1-5/vae/diffusion_pytorch_model.safetensors
          rm diffusion_pytorch_model.safetensors
