name: Dowload docker img and upload to Alicloud

on:
  workflow_dispatch:
    inputs:
      img:
        description: 'image to download, for instance, tensorflow/tensorflow'
        required: true
      accessKeyID:
        required: true
      accessKeySecret:
        required: true
      ossEndpoint:
        default: "oss-cn-beijing.aliyuncs.com"
        required: true
      ossPath:
        default: "oss://oneflow-static/img"
        required: true

jobs:
  downloadDockerImg:
    runs-on: ubuntu-latest
    steps:
    - run: |
      docker pull ${{ github.event.inputs.img }}
      gz_file="$(python3 sanitize_filename.py --img_name ${{ github.event.inputs.img }}).tar.gz"
      python3 -m pip install pathvalidate
      docker save ${{ github.event.inputs.img }} | gzip > ${gz_file}
      curl http://gosspublic.alicdn.com/ossutil/1.6.19/ossutil64 -o ossutil64
      chmod 755 ossutil64
      ./ossutil64 config -e ${{ github.event.inputs.ossEndpoint }} -i ${{ github.event.inputs.accessKeyID }} -k ${{ github.event.inputs.accessKeySecret }}  -L EN -c ./ossconfig
      ./ossutil64 --update cp ${gz_file} ${{ github.event.inputs.ossPath }}/${gz_file}
